version: "3.8"

services:
  # coderefactoring_api:
  #   build: ./coderefactoring_b
  #   restart: always

  #   expose:
  #     - "8000"

  sde1prep_api:
    build: ./sde1prep
    restart: always
    expose:
      - "8000"
    # Uncomment if you need environment variables from the .env file
    env_file:
      - ./sde1prep/.env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - coderefactoring_api
      - sde1prep_api
